import createClient from "openapi-fetch";
import {createApiClient} from "./lib/zoteroclient";
import type { paths } from "./lib/zoterotypes"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: "https://api.zotero.org",
});
const zclient = createApiClient("https://api.zotero.org");

client.GET('/groups/{groupId}/items', {
    params: {
        path: {
            groupId: '12345'
        },
        query: {
            limit: 50,
            start: 0,
        }
    }
}).then((res) => {
    let version = res.response.headers.get("Zotero-API-Versio");
    res.data.forEach((item) => {
      console.log(item.library);
    });
});

zclient.get("/groups/:groupId/items", {
    params: {
        groupId: "12345",
        limit: 50,
        start: 0,
    }
}).then((res) => {
  res.forEach((item) => {
    console.log(item.library);
  });
});