import createClient from "openapi-fetch";
import {createApiClient} from "./lib/zoteroclient";
import type { paths } from "./lib/zoterotypes"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: "https://api.zotero.org",
});
const zclient = createApiClient("https://api.zotero.org");

client.GET('/groups/{groupId}/items', {
    params: {
        path: {
            groupId: '12345'
        },
        query: {
            limit: 50,
            start: 0,
        }
    }
}).then((res) => {
    res.data.forEach((item) => {
      item.library.
    });
});

let zres = zclient.getItems({
    params: {
      groupId: '12345',
    },
    queries: {
        limit: 50,
        start: 0,
    }
})